name: CI/CD

on:
  push:
    paths:
      - installer/version.txt

jobs:
  build:
    name: TMA-1 configuration tool build
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.11 ]
        
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with: 
          python-version: 3.11
      - run: |
          python -m pip install --upgrade-pip
          pip install -r builder/config/requirements.txt
          pip install pyinstaller
